-- 1. Enable pgvector extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create topic master table
CREATE TABLE IF NOT EXISTS public.t_topics_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ko TEXT NOT NULL UNIQUE,     -- Topic Name (Korean)
    embedding vector(768),           -- Gemini text-embedding-004 is 768 dim
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE public.t_topics_master ENABLE ROW LEVEL SECURITY;

-- 4. Policy: Allow read access for everyone (for search/ranking)
CREATE POLICY "Enable read access for all users" ON public.t_topics_master
FOR SELECT USING (true);

-- 5. Policy: Allow insert/update only for service role (backend)
-- No public insert policy added for security.
